### ISSUE TITLE
Label for content element does not work

### ISSUE THREAD

**Issue by MySpace17** [IchHabRecht/mask_export#104]
The label for the contentelement does not work.

TYPO3: 8.7.8
mask_export: 0.9.1

I did cleared all caches.

![image](https://user-images.githubusercontent.com/33655465/32775057-a85c3f6c-c92e-11e7-977e-61e3a836373d.png)

**Comment by IchHabRecht** [comment]
Hi @MySpace17.

Would you mind to share your mask.json. I cannot analyse your problem with having your configuration. Thank you very much.

**Comment by MySpace17** [comment]
Hi @IchHabRecht.

It's not a bug. It's only that i've entered an extension name without "saving" it. I'd clicked on "download" directly.

Maybe a little notice next to the download button would be cool?

Btw, congrats to this cool extension!

**Comment by IchHabRecht** [comment]
Hi @MySpace17,

If you don't provide any extension key, a default one should be used.
