### ISSUE TITLE
mask-element "content" wouldn't be converted by mask_export

### ISSUE THREAD

**Issue by kurtkk** [IchHabRecht/mask_export#111]
What I told you. I've made some screenshots, look into the attached files. Attaching a json-file is not possible, so I'll copy the content and put it into this textbox:

1a. I created a mask-ce like this one:
![mask_export_2018-04-03_111510](https://user-images.githubusercontent.com/8299389/38242826-0e362dc8-3736-11e8-841c-bd41ed40249a.jpg)

1b. The raw data for the FE:
![mask_export_mask-fe-rohling-2018-04-03_112429](https://user-images.githubusercontent.com/8299389/38242824-0df6f6f8-3736-11e8-948f-4f47af35ade6.jpg)

2. I put one of them into a page with an CType TextMedia for the "mask-content-elment":
![mask_export_2018-04-03_112043](https://user-images.githubusercontent.com/8299389/38242825-0e172996-3736-11e8-92bd-7cd8e73b32f7.jpg)

3. I exported the mask-ce "kupix-mask_export-test" and imported the new Extension "kupix_mask_export_test_0.1.0_2018.... into another TYPO3 Account **without a mask-Extension**
![mask_export_2018-04-03_113652](https://user-images.githubusercontent.com/8299389/38242823-0dd77918-3736-11e8-8598-977e02780fe5.jpg)

4. I created a page CE type "kupix-qpxmaskexporttest_export-Test" and you see, that the field for the CType is empty
![mask_export_2018-04-03_114120](https://user-images.githubusercontent.com/8299389/38242821-0db1a972-3736-11e8-8621-d8e1cee60e0c.jpg)

5. The FE-result with the html-code - no CType "Text & Media":
![mask_export_2018-04-03_114430](https://user-images.githubusercontent.com/8299389/38242820-0d8e310e-3736-11e8-9e65-2137d507cf10.jpg)

6. The debug shows an empty array for that CE:
![mask_export_2018-04-03_114733](https://user-images.githubusercontent.com/8299389/38242818-0d676cea-3736-11e8-81c7-257f6483f4ab.jpg)

The mask.json:
**********************************************************************************************************
```
{
    "tt_content": {
        "elements": {
            "kupix": {
                "label": "kupix-mask_export-Test",
                "key": "kupix",
                "shortLabel": "kupix-mask_export-Test",
                "description": "kupix-Test \"Content\" nach mask_export",
                "icon": "fa-ambulance",
                "color": "#ff0000",
                "columns": [
                    "header",
                    "tx_mask_contentcontainer"
                ],
                "labels": [
                    "Titel \/ Name",
                    "Inhaltselement f\u00fcr den Test"
                ]
            }
        },
        "sql": {
            "tx_mask_contentcontainer": {
                "tt_content": {
                    "tx_mask_contentcontainer": "int(11) unsigned DEFAULT '0' NOT NULL"
                }
            }
        },
        "tca": {
            "tx_mask_contentcontainer": {
                "config": {
                    "type": "inline",
                    "foreign_table": "tt_content",
                    "overrideChildTca": {
                        "columns": {
                            "colPos": {
                                "config": {
                                    "default": "999"
                                }
                            }
                        }
                    },
                    "foreign_sortby": "sorting",
                    "appearance": {
                        "collapseAll": "1",
                        "levelLinksPosition": "top",
                        "showSynchronizationLink": "1",
                        "showPossibleLocalizationRecords": "1",
                        "showAllLocalizationLink": "1",
                        "useSortable": "1",
                        "enabledControls": {
                            "dragdrop": "1"
                        },
                        "expandSingle": "1",
                        "newRecordLinkTitle": ""
                    },
                    "minitems": "1",
                    "maxitems": "",
                    "behaviour": {
                        "localizeChildrenAtParentLocalization": "1"
                    }
                },
                "exclude": "1",
                "cTypes": [
                    "textmedia"
                ],
                "l10n_mode": "copy",
                "key": "contentcontainer"
            }
        }
    },
    "sys_file_reference": {
        "sql": {
            "tx_mask_card_image": {
                "sys_file_reference": {
                    "tx_mask_card_image": "int(11) unsigned DEFAULT '0' NOT NULL"
                }
            },
            "tx_mask_background_image": {
                "sys_file_reference": {
                    "tx_mask_background_image": "int(11) unsigned DEFAULT '0' NOT NULL"
                }
            },
            "tx_mask_bildresource": {
                "sys_file_reference": {
                    "tx_mask_bildresource": "int(11) unsigned DEFAULT '0' NOT NULL"
                }
            },
            "tx_mask_bild": {
                "sys_file_reference": {
                    "tx_mask_bild": "int(11) unsigned DEFAULT '0' NOT NULL"
                }
            }
        }
    },
    "pages": {
        "elements": {
            "1": {
                "label": "Standard - volle Breite",
                "key": "1",
                "shortLabel": "dummy shortitle",
                "description": "dummy description"
            }
        }
    }
}
```

**********************************************************************************************************

**Comment by IchHabRecht** [comment]
Hi @kurtkk,

Thanks for your reporting. It is quite hard to understand your screenshots without proper explanation.

So what I did:

1) I copied your provided json to my mask.json file (and clear cache in my TYPO3 installation)
Result:
![2018-04-03_183726](https://user-images.githubusercontent.com/1453345/38262631-1cd865b6-376e-11e8-8157-a3ebf4f35fae.jpg)

2) I triggered the export (direct installation) with extension key qpx_mask_export_test
Result:
[qpx_mask_export_test.zip](https://github.com/CPS-IT/mask_export/files/1872480/qpx_mask_export_test.zip)

3) I created a new page, included the static template from the extension in a sys_template record and created a new content element from the given CType
Result:
![2018-04-03_184100](https://user-images.githubusercontent.com/1453345/38262796-95eabc7e-376e-11e8-96af-dd63edec6359.jpg)

4) I opened the page in frontend and I'm able to see the content element and it's child
Result:
![2018-04-03_184156](https://user-images.githubusercontent.com/1453345/38262868-b48d146a-376e-11e8-863d-ffe75c477975.jpg)

Would you mind to explain the existing problem for you? Maybe you have missed, there are different data-keys in mask and the mask_export Fluid templates? What are your screenshots showing/telling?
Thank you for providing additional information.

**Comment by IchHabRecht** [comment]
Hi @kurtkk,

So you are working with two separate TYPO3 installations. Do they both use the same TYPO3 version? Which one? Do the both use same csc/fsc dependencies? Is the CType "textmedia" avalable in your second TYPO3 installation in general?

**Comment by kurtkk** [comment]
So you are working with two separate TYPO3 installations. 
>>> If you want to have a special Mask-CE in a fresch T3-Installation fpor a customer, then you'll install one, e.g. "qpx_mask_cards_0.1.0.zip". Do do not install mask and mask_export in that installation because you and the customer do not need them.

Do they both use the same TYPO3 version? Which one? 
>>> Yes, 8.7.12

Do the both use same csc/fsc dependencies?
>>> Yes

Is the CType "textmedia" avalable in your second TYPO3 installation in general?
>>> Yes

Would you mind to test the first TYPO3 installation with deactivate mask/mask_export extensions?
>>> This I wrote in my last posting in the last chapter:
First installation: the mask_export_test => the CE T&M wouldn't be displayed!?
Second installations: mask and mask_export AND Installtool: Compare database and delete 2 shown items of the mask_export_test AND Clear the chache => the CE T&M will be displayed!?
**_### After having deinstalled mask and mask_export again, the CE T&M wouldn't be displayed!_**

**Comment by kurtkk** [comment]
Sorry, but I cannot remember having closed the above mentioned problem ( post)!?
How can I open that topic again?

**Comment by IchHabRecht** [comment]
Hi @kurtkk,

I tried to reproduce your problem with two fresh TYPO3 8.7.12 installations, but I'm unable to reproduce. I think the problem is unfortunately on your site. Please check your error logs for additional information. Maybe you will find some helpful information in there.

**Comment by FooFights** [comment]
I seem to encounter the same problem as kurtkk using TYPO3 8.7.24. 

A contentelement using a contentcontainer is developed in System A and exported with mask export.

When I install the extension in SYSTEM B  **where mask is not installed** the contenttype-field of the CE is empty (see step 4 from kurtkk). After the installation of mask it works (like in step 2 from kurtkk) but that shouldn't be necessary or is that mandatory? It looks like mask brings some code to make it work.

Does the sole installation of mask affect the system's performance or is it bound to the use of the contentelements from whithin the mask extension?

**Comment by IchHabRecht** [comment]
Hi @FooFights,

I already tried to reproduce the problem in a completely new and fresh TYPO3 installation on my local system. As you may see in my answer https://github.com/IchHabRecht/mask_export/issues/111#issuecomment-378316631 I cannot find problem like both of you described. I'm pretty sure there are some inside changes that affect the CType generation before or after the export does. But without any access or more information about the context/installation I cannot help furthermore.
