### ISSUE TITLE
Nested elements are shown as "unused"

### ISSUE THREAD

**Issue by Haruki-Mortis** [IchHabRecht/mask_export#146]
Hi there,
i got some issue with nested elements.
In the frontend everything works perfect, but it seems there are some problems with the backend hook.
A thousend words say less then pictures, here we go:

![nested](https://user-images.githubusercontent.com/29275165/51913876-d3364200-23d7-11e9-818c-fbeb159f4510.PNG)
![unused](https://user-images.githubusercontent.com/29275165/51913879-d4676f00-23d7-11e9-8c3b-7e86148a8eea.PNG)

If mask is installed the issue disappears.

Typo3 9.5.4 LTS

**Comment by IchHabRecht** [comment]
Hi @Haruki-Mortis,

Thank you for your report. There is no issue with the export itself. You can find an extension that will help you here https://extensions.typo3.org/extension/hide_used_content/

Hope this will help to solve your problem.

**Comment by Haruki-Mortis** [comment]
Fast answer, thank you.

This sloved my problem very well.
