### ISSUE TITLE
Backend Image Preview

### ISSUE THREAD

**Issue by hagerp** [IchHabRecht/mask_export#147]
Is there an easy way to view processed images in the Backend View?

My Workaround now:

<f:for each="{processedRow.image}" as="item">
    <f:for each="{item.uid_local}" as="file">
        < img src="/fileadmin/{file.row.identifier}" style="width: 200px;height: auto;" />
    </f:for>

<f:image> is not working

**Comment by IchHabRecht** [comment]
Hi @hagerp,

You can just use the information you find in the example (default) template provided with the export:

<f:for each="{processedRow.tx_mymaskexport_images}" as="item">
    <f:image src="{item.uid}" treatIdAsReference="1" />
</f:for>

or for your case:

<f:for each="{processedRow.image}" as="item">
	<f:for each="{item.uid_local}" as="file">
		<f:image src="{file.uid}" width="200" />
	</f:for>
</f:for>

Hope this helps to solve your problem.

**Comment by IchHabRecht** [comment]
This issue will be closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience a problem.
