### ISSUE TITLE
Order of fields within an exported content element

### ISSUE THREAD

**Issue by anglee72** [IchHabRecht/mask_export#158]
Hi, I have a problem with the order of the rendered fields of a content element in the BE.
I guess the 
    "order" => 4 
in the exported Configuration/TCA file should do the job?

'columns' =>
        array (
           'tx_myprovider_myfourthfield' =>
                array (
                    'config' =>
                        array (
                            'type' => 'input',
                        ),
                    'exclude' => '1',
                    'label' => 'That's my Label',
                    'order' => 4,
                ),

Or the "order": 4 in the mask.json?

            "tx_myprovider_myfourthfield": {
                "config": {
                    "default": "",
                    "eval": "",
                    "max": "",
                    "placeholder": "",
                    "size": "",
                    "type": "input"
                },
                "exclude": "1",
                "inlineParent": "tx_mask_appartement",
                "key": "appartemnttype",
                "l10n_mode": "",
                "label": "A Label",
                "order": 4
            },

But none of these affects the ordering of the fields within the content element in the BE ... 
What is the "order": 4 then doing and now to order the fields?

Sorry, I'm not at all skilled in extension programming ...
Can you help? Thanks!

**Comment by IchHabRecht** [comment]
Hi @anglee72,

I have to admit that I don't exactly understand your problem. The ordering of the fields within a content element is coming from the ordering of the fields within your mask configuration and can be seen on opening the content element in the mask wizard. The export does not created any own TCA information but uses the ones generated by mask itself. Can you try to re-arrange the desired field configuration in your (mask) content element?!

**Comment by anglee72** [comment]
Thank you for your quick respond ... I wanted to change the order in the exported extension. I know, that's not a recommended thing to do ... anyway.

The order of the fields (BE) is not obvious to me and does not correspond to the order in the TCS configuration file or the one in the Json file and apparently does not come from the DB - as far as I can see. It seems as if the order is random.
The order must be stored in the extension somehow, since it is now completely independent of the mask ext. and I'm pretty sure there must be a way to manipulate it afterwards. 

But you don't have to do anything else, I'll keep trying to find a solution myself. 
Thanks!

**Comment by IchHabRecht** [comment]
Hi @anglee72,

You can find the sorting of the fields in the file Configuration/TCA/Overrides/tt_content.php
There you will find `showitem` configurations for each of your content element that contains the order of the fields. Still the order of your fields should be the same like in your mask backend module. If you really need to change the ordering "manually" I would suggest to override the TCA configuration within your sitepackage extension and leave the export untouched.

**Comment by anglee72** [comment]
Thank you very much for your help! I will try to configure the order it this way!

**Comment by IchHabRecht** [comment]
Hi @anglee72,

I'm closing this issue as no response came up lately.
