### ISSUE TITLE
Service Unavailable

### ISSUE THREAD

**Issue by Gatnos** [IchHabRecht/mask_export#165]
Hey,

I don't know what happen, but after my configuration in mask i can not open mask_export anymore.
I keep getting the error "Service Unavailable".

![typo3error](https://user-images.githubusercontent.com/15328257/86107035-9b966280-bac1-11ea-8f15-6d7927e33024.png)

I've tried another typo3 v10 system, and there it is working, tried to uninstall and reinstall the extension, cleared the database and nothing works. All other modules works correctly.

Can you help me please?

Armin

**Comment by IchHabRecht** [comment]
Hi @Gatnos,

Unfortunately I'm unable to help here. Please check your server/error logs and might come up with more information.

**Comment by Gatnos** [comment]
Hey Nicole,

mein Server Log zeigt aktuell keine Fehlermeldungen an.
Ich habe mal in die Logs von Typo3 geschaut, kann jedoch aber nicht viel mit der Aussage anfangen:

Tue, 30 Jun 2020 13:18:53 +0200 [ERROR] request="c3b8ef86dad9f" component="TYPO3.CMS.Backend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed. - {"expression":"maskBeLayout(simple)"}


Hier ist noch die Log-Datei, falls du die sehen magst:
[typo3_19bbd14fbb.log](https://github.com/IchHabRecht/mask_export/files/4851419/typo3_19bbd14fbb.log)

**Comment by IchHabRecht** [comment]
Hallo @Gatnos,

ich kann dir hier leider keinen Support geben. Die Fehlermeldung besagt, dass eine Komponente des TypoScripts einen Fehler verursacht. Ich kann hier aber den Export selbst ausschließen. Bitte checke mal dein TypoScript auf Fehler.

**Comment by Gatnos** [comment]
Danke trotzdem, auch wenn ich mir das nicht vorstellen kann, da ich das TypoScript nicht mehr angefasst habe und davor funktionierte Mask Export einwandfrei.
