### ISSUE TITLE
Compatibility with mask v.6

### ISSUE THREAD

**Issue by ap1337** [IchHabRecht/mask_export#170]
Hi, 

are there plans making mask_export work with mask v6 on Typo3 v10?

Thanky you,
alex

**Comment by IchHabRecht** [comment]
Hi @ap1337,

tests are still running so I updated the constraints and it should be compatible with the new version.

**Comment by ap1337** [comment]
Hi @IchHabRecht,

thank you very much! I'll try it out!

**Comment by ap1337** [comment]
Hi @IchHabRecht,

exporting, activating and working with content elements works fine. Thank you!

My Test-Setup: Typo3 v10.4.9 in composer setup, mask v6.2, mask_export v3.0.3

**Comment by IchHabRecht** [comment]
Hi @ap1337,

Thanks for your feedback. So I close this issue then.
