### ISSUE TITLE
Preview icon, wrong path (Extension.svg)

### ISSUE THREAD

**Issue by cgpro** [IchHabRecht/mask_export#174]
When exporting, a file Extension.svg is created within the new extension folder. But in the code it says Extension.png
(public/typo3conf/ext/klaka_ce/Resources/Public/Icons/Extension.svg)

<img width="1025" alt="Bildschirmfoto 2021-01-25 um 16 47 48" src="https://user-images.githubusercontent.com/1557147/105729090-25f65600-5f2d-11eb-85e2-19a32a0b81bf.png">

public/typo3conf/ext/mask_export/Classes/Aggregate/TcaAggregate.php (Line 55)

Wrong:
`$tcaConfiguration['ctrl']['iconfile'] = 'EXT:mask/Resources/Public/Icons/Extension.png';`

Correct:
`$tcaConfiguration['ctrl']['iconfile'] = 'EXT:mask/Resources/Public/Icons/Extension.svg';`

You could consider this for the next release. 😊

TYPO3-Version: 10.4.12

**Comment by IchHabRecht** [comment]
Hi @cgpro,

This issue should be solved with #177
