### ISSUE TITLE
Parent field in TCA

### ISSUE THREAD

**Issue by kitzberger** [IchHabRecht/mask_export#175]
We're currently trying to add a copy/paste feature into our container elements we've created with mask. For TYPO3's DataHandler to update the pasted CE it needs to be able to find the "parent" field within the columns array of tt_content's TCA.

In our case it was sufficient to provide this additional TCA here:
```
// Having the parent field present in TCA is mandatory for TYPO3's DataHandler
// to be able to use those fields when updating records via /ajax/record/process
$GLOBALS['TCA']['tt_content']['columns']['tx_ourextension_accordion_items_parent'] = [
    'config' => [
        'type' => 'passthrough'
    ],
];
```

I'm not quite sure if this is a EXT:mask oder an EXT:mask_export issue.

Our goal is to maybe come up with a handy viewhelper to be used within the backend templates to achieve copy/paste and if possible dragndrop functionality for our editos.

**Comment by IchHabRecht** [comment]
Hi @kitzberger,

Thank you for your issue. As mask_export only uses TCA information generated by mask, this issue needs to be solved on mask side. As soon as it is available in the generated TCA, mask_export is able to output it.

**Comment by kitzberger** [comment]
@IchHabRecht, thanks for clarification ;-) I've "moved" this issue to mask's tracker: https://github.com/Gernott/mask/issues/389
