### ISSUE TITLE
Export element to extension and use it standalone

### ISSUE THREAD

**Issue by Garb-in-PacK** [IchHabRecht/mask_export#181]
Hello! Please anyone explain me how to export mask elements correct? i export some element to extension on my first typo3 server and download it to the second server but elemebts dont work. typo3 and mask versions are same.

**Comment by IchHabRecht** [comment]
Hi @Garb-in-PacK,

Have you selected any elements to be included in the export? Have you installed the export extension in the second TYPO3 installation? Which versions of TYPO3 are you using. On the second server you should not install mask anymore as this is the purpose of your exported extension.
